#!/bin/bash

cd ..

COUNT=0
CURRENT_DIR="$PWD"
PD="build-tools/patches"
PATCHES=()

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	git apply "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
