#!/bin/bash

cd ./..
ROOT_DIR=$(pwd)
BUILD_TOOLS_DIR=$ROOT_DIR/build_tools
PATCHES_DIR=$BUILD_TOOLS_DIR/patches

echo -n 'Patching... '

for diff_file in $(ls $PATCHES_DIR | grep -E ".*.(diff|patch)$")
do
	cd $ROOT_DIR/$(echo $diff_file | sed -E 's/_/\//g; s/.(diff|patch)//')
	
	if [ "$1" == "-c" ]; then
        git reset --hard > /dev/null
	fi
	
	git apply $PATCHES_DIR/$diff_file || exit -1
done

cd $BUILD_TOOLS_DIR

echo 'done'

