#!/bin/bash

cd ./..
ROOT_DIR=$(pwd)

echo -n 'Clearing... '
repo forall -c "git reset --hard && git clean -fdx" > /dev/null && echo 'done'

if [ "$1" == "-s" ]; then
    echo -n 'Syncing... '
	repo sync > /dev/null && echo 'done'
fi

